[package]
name = "libwebp-sys"
version = "0.1.0"
authors = [ "Greg V <greg@unrelenting.technology>" ]
keywords = [ "WebP", "Image", "Picture", "Photo", "Codec", "Decoder", "Encoder" ]
description = "Bindings to libwebp (bindgen, static linking)"
license = "BSD"
readme = "README.md"

build = "build.rs"

[build-dependencies]
cmake = "0.1"